## Installing Libraries

In [1]:
!pip install pysmiles

Requirement already satisfied: pysmiles in /home/qc1/QNetGAN/qnetgan/lib/python3.8/site-packages (1.1.2)
Requirement already satisfied: networkx in /home/qc1/QNetGAN/qnetgan/lib/python3.8/site-packages (from pysmiles) (2.8.4)
Requirement already satisfied: pbr in /home/qc1/QNetGAN/qnetgan/lib/python3.8/site-packages (from pysmiles) (6.0.0)

## Importing libraries

In [2]:
import pandas as pd
from pysmiles import read_smiles
import networkx as nx
import matplotlib.pyplot as plt
from rdkit import Chem
from rdkit.Chem.rdMolDescriptors import CalcMolFormula

## Preprocessing QM9 Smiles Dataset

In [3]:
smiles_dfwH = pd.read_csv("OriginalSMILES_QM9.csv")
smiles_dfwH = smiles_dfwH.drop('idx', axis=1)
# smiles_dfwoH = pd.read_csv("OriginalSMILES_QM9.csv")
# smiles_dfwoH = smiles_dfwoH.drop('idx', axis=1)

In [4]:
smiles_dfwH

                     smiles
0                         C
1                         N
2                         O
3                       C#C
4                       C#N
...                     ...
132035  C1C2C3C4C5OC14C5N23
132036  C1N2C3C2C2C4OC12C34
132037  C1N2C3C4C5C2C13CN45
132038  C1N2C3C4C5CC13C2C45
132039  C1N2C3C4C5OC13C2C45

[132040 rows x 1 columns]

In [5]:
# smiles_dfwoH

## Converting SMILES to Graph Representation

In [6]:
molmatrixwH = []
# molmatrixwoH = []

for i in range(len(smiles_dfwH)):
  molwH = read_smiles(smiles_dfwH['smiles'][i], explicit_hydrogen=True)
  molmatrixwH.append(nx.to_numpy_matrix(molwH))
  # molwoH = read_smiles(smiles_dfwoH['smiles'][i], explicit_hydrogen=False)
  # molmatrixwoH.append(nx.to_numpy_matrix(molwoH))

In [7]:
countwH = 0

for i in range(len(smiles_dfwH)):
  if len(molmatrixwH[i]) <= 11:
      countwH += 1

In [8]:
lenwH = []

for i in range(len(smiles_dfwH)):
  lenwH.append(len(molmatrixwH[i]))

In [9]:
formulaList = []

for i in range(len(smiles_dfwH)):
    mol = Chem.MolFromSmiles(smiles_dfwH.iloc[i]['smiles'])
    formula = CalcMolFormula(mol)
    formulaList.append(formula)

In [10]:
# countwoH = 0

# for i in range(len(smiles_df)):
#   if len(molmatrixwoH[i]) <= 11:
#       countwoH += 1

In [11]:
# lenwoH = []

# for i in range(len(smiles_dfwoH)):
#   lenwoH.append(len(molmatrixwoH[i]))

In [12]:
# lenwoH

In [13]:
smiles_dfwH['formula'] = formulaList
smiles_dfwH['matrixwH'] = molmatrixwH
smiles_dfwH['lenwH'] = lenwH
# smiles_dfwoH['matrixwoH'] = molmatrixwoH
# smiles_dfwoH['lenwoH'] = lenwoH

In [14]:
# smiles_dfwH = smiles_dfwH.drop(smiles_dfwH[smiles_dfwH['lenwH'] > 11].index)
# smiles_dfwoH = smiles_dfwoH.drop(smiles_dfwoH[smiles_dfwoH['lenwoH'] > 11].index)

In [15]:
# smiles_dfwH = smiles_dfwH.reset_index()
# smiles_dfwH = smiles_dfwH.drop('index', axis=1)
# smiles_dfwoH = smiles_dfwoH.reset_index()

In [16]:
# smiles_dfwoH

In [17]:
smiles_dfwH

,smiles,formula,matrixwH,lenwH
0,C,CH4,"[[[[[0. 1. 1. 1. 1.]]]], [[[[1. 0. 0. 0. 0.]]]...",5
1,N,H3N,"[[[[[0. 1. 1. 1.]]]], [[[[1. 0. 0. 0.]]]], [[[...",4
2,O,H2O,"[[[[[0. 1. 1.]]]], [[[[1. 0. 0.]]]], [[[[1. 0....",3
3,C#C,C2H2,"[[[[[0. 1. 1. 0.]]]], [[[[1. 0. 0. 1.]]]], [[[...",4
4,C#N,CHN,"[[[[[0. 1. 1.]]]], [[[[1. 0. 0.]]]], [[[[1. 0....",3
...,...,...,...,...
132035,C1C2C3C4C5OC14C5N23,C7H7NO,[[[[[0. 1. 0. 0. 0. 0. 1. 0. 0. 1. 1. 0. 0. 0....,16
132036,C1N2C3C2C2C4OC12C34,C7H7NO,[[[[[0. 1. 0. 0. 0. 0. 0. 1. 0. 1. 1. 0. 0. 0....,16
132037,C1N2C3C4C5C2C13CN45,C7H8N2,[[[[[0. 1. 0. 0. 0. 0. 1. 0. 0. 1. 1. 0. 0. 0....,17
132038,C1N2C3C4C5CC13C2C45,C8H9N,[[[[[0. 1. 0. 0. 0. 0. 1. 0. 0. 1. 1. 0. 0. 0....,18
132039,C1N2C3C4C5OC13C2C45,C7H7NO,[[[[[0. 1. 0. 0. 0. 0. 1. 0. 0. 1. 1. 0. 0. 0....,16

In [18]:
smiles_csv_data = smiles_dfwH.to_csv('Graph_QM9_Hydrogens.csv', index = True)

In [19]:
# Draws the graph of a particular molecule

# elements = nx.get_node_attributes(mol, name = "element")
# nx.draw(mol, with_labels=True, labels = elements, pos=nx.spring_layout(mol))
# plt.gca().set_aspect('equal')